/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/action/index.vue')['default']
    ActionForm: typeof import('./src/components/action/actionForm.vue')['default']
    Blank: typeof import('./src/components/page/blank.vue')['default']
    ComDetail: typeof import('./src/components/com/comDetail/index.vue')['default']
    ComDialogModal: typeof import('./src/components/com/comDialogModal/index.vue')['default']
    ComField: typeof import('./src/components/com/comField/index.vue')['default']
    ComFieldCopy: typeof import('./src/components/com/comField/comFieldCopy.vue')['default']
    ComFieldDetail: typeof import('./src/components/com/comField/comFieldDetail.vue')['default']
    ComFieldDialog: typeof import('./src/components/com/comField/comFieldDialog.vue')['default']
    ComFieldEnum: typeof import('./src/components/com/comField/comFieldEnum.vue')['default']
    ComFieldTable: typeof import('./src/components/com/comField/comFieldTable.vue')['default']
    ComForm: typeof import('./src/components/com/comForm/index.vue')['default']
    ComTable: typeof import('./src/components/com/comTable/index.vue')['default']
    ComTableAdvSearch: typeof import('./src/components/com/comTable/comTableAdvSearch.vue')['default']
    ComTableOptions: typeof import('./src/components/com/comTable/comTableOptions.vue')['default']
    ComTableSearch: typeof import('./src/components/com/comTable/comTableSearch.vue')['default']
    DataTable: typeof import('./src/components/page/dataTable/index.vue')['default']
    DataTableAdvSearch: typeof import('./src/components/page/dataTable/dataTableAdvSearch.vue')['default']
    DataTableOptions: typeof import('./src/components/page/dataTable/dataTableOptions.vue')['default']
    DataTableSearch: typeof import('./src/components/page/dataTable/dataTableSearch.vue')['default']
    Header: typeof import('./src/components/layout/header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Logo: typeof import('./src/components/layout/logo.vue')['default']
    MenuItems: typeof import('./src/components/layout/sidebar/menuItems.vue')['default']
    Page: typeof import('./src/components/page/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/sidebar/index.vue')['default']
    Tabs: typeof import('./src/components/layout/tabs/index.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
